In [1]:
import pandas as pd

In [2]:
import os

print(os.getcwd())

C:\Users\gpran\Desktop\MPLADS\notebooks

In [3]:
print(os.listdir())

['.ipynb_checkpoints', '01_data_understanding.ipynb']

In [4]:
from pathlib import Path

base = Path.cwd().parent

print("MPLADS folder:", base)
print("\nContents:")
for item in base.rglob("*"):
    print(item)

MPLADS folder: C:\Users\gpran\Desktop\MPLADS

Contents:
C:\Users\gpran\Desktop\MPLADS\data
C:\Users\gpran\Desktop\MPLADS\notebooks
C:\Users\gpran\Desktop\MPLADS\README.md.txt
C:\Users\gpran\Desktop\MPLADS\reports
C:\Users\gpran\Desktop\MPLADS\requirements.txt.txt
C:\Users\gpran\Desktop\MPLADS\src
C:\Users\gpran\Desktop\MPLADS\data\ml_ready
C:\Users\gpran\Desktop\MPLADS\data\processed
C:\Users\gpran\Desktop\MPLADS\data\raw
C:\Users\gpran\Desktop\MPLADS\notebooks\.ipynb_checkpoints
C:\Users\gpran\Desktop\MPLADS\notebooks\01_data_understanding.ipynb
C:\Users\gpran\Desktop\MPLADS\notebooks\.ipynb_checkpoints\01_data_understanding-checkpoint.ipynb
C:\Users\gpran\Desktop\MPLADS\data\raw\MPLADS_Lok_Sabha.xlsx
C:\Users\gpran\Desktop\MPLADS\data\raw\MPLADS_Rajya_Sabha.xlsx

In [5]:
from pathlib import Path
import pandas as pd

BASE_DIR = Path.cwd().parent

lok_path = BASE_DIR / "data" / "raw" / "MPLADS_Lok_Sabha.xlsx"
rajya_path = BASE_DIR / "data" / "raw" / "MPLADS_Rajya_Sabha.xlsx"

lok_df = pd.read_excel(lok_path)
rajya_df = pd.read_excel(rajya_path)

print("Lok Sabha shape:", lok_df.shape)
print("Rajya Sabha shape:", rajya_df.shape)

Lok Sabha shape: (544, 5)
Rajya Sabha shape: (232, 5)

In [6]:
print("LOK SABHA COLUMNS:")
print(lok_df.columns.tolist())

print("\nRAJYA SABHA COLUMNS:")
print(rajya_df.columns.tolist())

LOK SABHA COLUMNS:
['Sr. No.', 'State', "Hon'ble Members of Parliaments", 'Constituency', 'Allocated AMOUNT ( ₹ )']

RAJYA SABHA COLUMNS:
['Sr. No.', 'State', "Hon'ble Members of Parliament", 'Elected/Nominated', 'Allocated AMOUNT ( ₹ )']

In [7]:
print("LOK SABHA - FIRST 5 ROWS")
display(lok_df.head())

print("\nRAJYA SABHA - FIRST 5 ROWS")
display(rajya_df.head())

LOK SABHA - FIRST 5 ROWS

,Sr. No.,State,Hon'ble Members of Parliaments,Constituency,Allocated AMOUNT ( ₹ )
0,1,Maharashtra,AASHTIKAR PATIL NAGESH BAPURAO,HINGOLI,190289442
1,2,Jammu And Kashmir,ABDUL RASHID SHEIKH,BARAMULLAH,154773472.1
2,3,Bihar,ABHAY KUMAR SINHA,AURANGABAD_BR,147000000
3,4,West Bengal,ABHIJIT GANGOPADHYAY,TAMLUK,147000000
4,5,West Bengal,Abu Taher Khan,MURSHIDABAD,147000000

RAJYA SABHA - FIRST 5 ROWS

,Sr. No.,State,Hon'ble Members of Parliament,Elected/Nominated,Allocated AMOUNT ( ₹ )
0,1,Telangana,Dr. Abhishek Manu Singhvi (2026-32) (2026-2032),Elected MP,73421449
1,2,Maharashtra,Dr. Ajeet Madhavrao Gopchade (2024-30) (2024-2...,Elected MP,147000000
2,3,Rajasthan,Dr. Alka Singh (2026-32) (2026-2032),Elected MP,49000000
3,4,Tamil Nadu,Dr. Anbumani Ramadoss (2026-32) (2026-2032),Elected MP,49356476.5
4,5,Maharashtra,Dr. Anil Sukhdeorao Bonde (2022-28) (2022-2028),Elected MP,196063957.1

In [8]:
print("===== LOK SABHA INFO =====")
lok_df.info()

print("\n===== RAJYA SABHA INFO =====")
rajya_df.info()

===== LOK SABHA INFO =====
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 544 entries, 0 to 543
Data columns (total 5 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Sr. No.                         544 non-null    object
 1   State                           544 non-null    object
 2   Hon'ble Members of Parliaments  544 non-null    object
 3   Constituency                    544 non-null    object
 4   Allocated AMOUNT ( ₹ )          543 non-null    object
dtypes: object(5)
memory usage: 21.4+ KB

===== RAJYA SABHA INFO =====
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 232 entries, 0 to 231
Data columns (total 5 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Sr. No.                        232 non-null    object
 1   State                          232 non-null    object
 2   Hon'ble Members of Parliament  232 non-null    object
 3   Elected/Nominated              232 non-null    object
 4   Allocated AMOUNT ( ₹ )         232 non-null    object
dtypes: object(5)
memory usage: 9.2+ KB

In [9]:
print("===== LOK SABHA MISSING VALUES =====")
print(lok_df.isnull().sum())

print("\n===== RAJYA SABHA MISSING VALUES =====")
print(rajya_df.isnull().sum())

===== LOK SABHA MISSING VALUES =====
Sr. No.                           0
State                             0
Hon'ble Members of Parliaments    0
Constituency                      0
Allocated AMOUNT ( ₹ )            1
dtype: int64

===== RAJYA SABHA MISSING VALUES =====
Sr. No.                          0
State                            0
Hon'ble Members of Parliament    0
Elected/Nominated                0
Allocated AMOUNT ( ₹ )           0
dtype: int64

In [10]:
print("LOK SABHA - ROW WITH MISSING ALLOCATION:")
display(lok_df[lok_df["Allocated AMOUNT ( ₹ )"].isnull()])

LOK SABHA - ROW WITH MISSING ALLOCATION:

,Sr. No.,State,Hon'ble Members of Parliaments,Constituency,Allocated AMOUNT ( ₹ )
107,108,Maharashtra,CHAVAN VASANTRAO BALWANTRAO,NANDED,NaN

In [11]:
print("Lok Sabha exact duplicate rows:", lok_df.duplicated().sum())
print("Rajya Sabha exact duplicate rows:", rajya_df.duplicated().sum())

Lok Sabha exact duplicate rows: 0
Rajya Sabha exact duplicate rows: 0

In [12]:
print("LOK SABHA - LAST 5 ROWS")
display(lok_df.tail())

print("\nRAJYA SABHA - LAST 5 ROWS")
display(rajya_df.tail())

LOK SABHA - LAST 5 ROWS

,Sr. No.,State,Hon'ble Members of Parliaments,Constituency,Allocated AMOUNT ( ₹ )
539,540,Andhra Pradesh,Y S Avinash Reddy,KADAPA,156430260.1
540,541,Karnataka,YADUVEER KRISHNADATTA CHAMARAJA WADIYAR,MYSORE,147000000
541,542,Delhi,Yogendra Chandoliya,NORTH WEST DELHI(SC),147876307
542,543,Uttar Pradesh,ZIA UR REHMAN,SAMBHAL,147000000
543,Grand Total,,,,"83,18,05,53,325.71"

RAJYA SABHA - LAST 5 ROWS

,Sr. No.,State,Hon'ble Members of Parliament,Elected/Nominated,Allocated AMOUNT ( ₹ )
227,228,Rajasthan,Smt. Sonia Gandhi (2024-30) (2024-2030),Elected MP,147000000
228,229,Karnataka,Smt. Sudha Murty (2024-30) (2024-2030),Nominated MP,147000000
229,230,Odisha,Smt. Sulata Deo (2022-28) (2022-2028),Elected MP,196084721.4
230,231,Madhya Pradesh,Smt. Sumitra Balmik (2022-28) (2022-2028),Elected MP,196063957.1
231,Grand Total,,,,"33,63,84,82,301.82"